# fly.toml app configuration file generated for cs-375-project-lively-snow-6801 on 2023-12-15T11:32:39-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cs-375-project-lively-snow-6801"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
